# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dce3a8072cc0e7a5173ab9015f3cf4fde8927d6eb9c8bd9cacab5aefcac6803785b911838b68adc11a42904d973991ec1f634f596a0d877818e707b7c66521b

test:
  secret_key_base: 52317ef4fdedf0b47c0413324e5d6dd45ee8bafd2f2faf56230eb583d8ebe0f040cfc59aba7058e8850b38825cf03a23af45041129bf38236698f92df36448a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
